GET http://localhost:3000/api/tweet

###

PATCH http://localhost:3000/api/tweet
Content-Type: application/json

{
    "id": "68f86d22530e0eb6cd316d1d",
    "newLabel": 7
}

###
GET http://localhost:3000/api/user?id=68e24ab75c591cce776f245d



###
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "first_Name": "Test",
    "last_Name": "Test",
    "age": 21,
    "sex": "m",
    "email": "TEST@gmail.com",
    "password": "test"
}

###
Patch http://localhost:3001/api/user
Content-Type: application/json

{
    "id": "68dd0047747b63e5dc91d56e"

}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "TEST@gmail.com",
    "password": "test"
}